name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Login to Amazon ECR
      #   run: |
      #     aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

      # - name: Build and push Docker image to ECR
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: ${{ secrets.ECR_REPOSITORY }}:latest
      #     cache-from: type=registry,ref=${{ secrets.ECR_REPOSITORY }}:cache
      #     cache-to: type=registry,ref=${{ secrets.ECR_REPOSITORY }}:cache,mode=max

      - name: Deploy to EC2 and run container
        environment: Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/carpool-connect-backend
            sudo git switch main
            sudo git pull

      #       # Log in to ECR on the EC2 instance
      #       aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

      #       # Stop and remove any running container (if applicable)
      #       if [ $(docker ps -q --filter "name=my-container") ]; then
      #         docker stop my-container
      #         docker rm my-container
      #       fi

      #       # Pull the latest image from ECR
      #       docker pull ${{ secrets.ECR_REPOSITORY }}:latest

      #       # Run the container (adjust ports, volume mounts, and environment variables as needed)
      #       docker run -d --name my-container -p 80:80 ${{ secrets.ECR_REPOSITORY }}:latest
